### ISSUE TITLE
some features

### ISSUE THREAD

**Issue by ozbillwang** [alexharv074/jira_worklog#2]
1. generate a list I worked in last several days, such as

```

---
server: 'jira.example.com'
username: 'james'
infill: '8h'
days: '5d'    <= default history I need get. 
```

it will generate a data.yml file as below:

```

---
worklog:
  '2016-04-14':
  - DEV-6233: 
    subject: abc
  - PROJ-4123:
     subject: abc
  - DEV-6300: 
     subject: abc
  2016-04-15:
  - PROJ-41 
     subject: abc
```
1. I can update the data.yml with the time I involved. 
2. run the ruby script `jira_worklog.rb` to upload the time.
